"""empty message

Revision ID: 3509ec59b5c5
Revises: abb1f0e612d0
Create Date: 2022-05-22 10:26:48.740947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3509ec59b5c5'
down_revision = 'abb1f0e612d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
